apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner-deployment
  namespace: {{ .Release.Namespace }}

spec:
  template:
    spec:
      image: {{ .Values.repository }}:{{ .Values.tag }}
      dockerdWithinRunnerContainer: {{ .Values.dockerInDocker }}
      organization: {{ .Values.organization }}
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
      group: {{ .Values.runnerGroup }}
      {{- if .Values.volumeMounts }}
      {{- range .Values.volumeMounts }}
      volumeMounts:
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
      {{- end }}
      {{- range .Values.volumeMounts }}
      volumes:
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: DirectoryOrCreate
      {{- end }}
      {{- end }}
      dockerEnabled: false
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      {{- if .Values.maxRunnersPerNode }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.maxRunnersPerNode }}
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              runner-deployment-name: github-runner-deployment
      {{- end }}
